version: '3.0'

services:
    php-fpm:
        build:
            context: ./_docker/php-fpm
            dockerfile: Dockerfile
        volumes:
            - ./app:/symfony
        container_name: ${PROJECT_NAME}_php-fpm
        ports:
            - '8080:8080'
        depends_on:
            - postgres

    php-cli:
        build:
            context: ./_docker/php-cli
        volumes:
            - ./app:/symfony
        command: sleep 10000
        container_name: ${PROJECT_NAME}_php-cli
        depends_on:
            - php-fpm

    postgres:
        restart: always
#        image: postgres:${POSTGRES_VERSION:-14}-alpine
        image: postgres
        container_name: ${PROJECT_NAME}_db
        environment:
            POSTGRES_DB: ${POSTGRES_DATABASE}
            # You should definitely change the password in production
            POSTGRES_PASSWORD: root
            POSTGRES_USER: root
        volumes:
            - postgres:/var/lib/postgresql/data:rw
        ports:
            -   '5432:5432'

volumes:
    postgres:
