controllers:
    resource: ../src/Controller/
    type: attribute

app_home:
    path: /
    controller: App\Controller\HomeController::index

app_catalog:
    path: /catalog
    controller: App\Controller\CatalogController::index
